node:
  site: site1
  name: "du10"
  role: worker
  technology: 5gmmw
  net_function: du_001
  hw_profile: lenovo-sr650
  # hint to try and deploy the RHCOS tro the correct disk
  # for given platform including VMs
  boot_dev_hint: /dev/sda
  # set to true if not installing on SSD or NVMe, example spinning HDD
  boot_spinner_hint: false
  lso: "false"
  ocs: "false"
  node_labels:
    ran.openshift.io/sriov: ''
    ran.openshift.io/oran-mh-vfio: ''
    ran.openshift.io/oran-mh-netdevice: ''
    ran.openshift.io/oran-bh-vfio: ''
  node_annotations:
    kubernetes.io/description: 'test annotation du10'
  # IP will be applied to either the bond interface (if enabled) or the 1st interface in the "interfaces" list
  IP: "10.198.7.169"
  prefix_length: 26
  #Assumes 1st "bond_members" interface(s) in "interface list" forms the bond
  bond_enable: "false"
  bond_name: bond0
  bond_members: "2"
  bond_mode: active-backup
  #
  int_mtu: 9000
  #3CFDFEE3AD1D	3CFDFEE3AD1C			3868DD0E49C0	3868DD0E49C1	3868DD0E49C2	3868DD0E49C3
  interfaces:
  - name: "ens4f0"
    mac: "3c:fd:fe:e3:ad:1d"
  - name: "ens4f1"
    mac: "3c:fd:fe:e3:ad:1c"
  - name: "eno1"
    mac: "38:68:dd:0e:49:c0"
  - name: "eno2"
    mac: "38:68:dd:0e:49:c1"
  - name: "eno3"
    mac: "38:68:dd:0e:49:c2"
  - name: "eno4"
    mac: "38:68:dd:0e:49:c3"
  bmc_username: USERID
  bmc_password: PASSW0RD
  bmc_address: redfish-virtualmedia+https://10.198.0.72/redfish/v1/Systems/1
