---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: preinstall-{{ $.Values.cluster.name }}-wait-{{ $.Values.node.name }}-job
  namespace: {{ $.Values.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ $.Values.gitops.hook_image }}
          imagePullPolicy: IfNotPresent
          name: {{ $.Values.cluster.name }}-{{ $.Values.node.name }}-wait-ready-job
          env:
            - name: SLEEP
              value: "15"
          command:
            - /bin/bash
            - -c
            - |
              echo "Cluster Pre Install Hook"
              URL_READY="Pausing $SLEEP seconds..."
              CSV_STATUS="Pausing $SLEEP seconds..."
              while [ "$CSV_STATUS" != "Ready" ]; do
                echo "Waiting for worker {{ $.Values.node.name }} to be ready. ($CSV_STATUS)"
                sleep $SLEEP
                CSV_STATUS=$( oc get nodes | egrep {{ $.Values.node.name }} | awk '{print $2}' )
              done
              echo "All done! Hooray!"


